site_name: Proxmox

nav:
  - Home: index.md
  - About: about.md
  - VMs:
      - Distributions:
          - vms/distributions.md
          - VPN: vms/vpn-ubunto.md
      - BackUps: vms/backups.md
      - SnapShots: vms/snapshots.md

theme: readthedocs
